In [ ]:
#Upload the data
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('/content/femicide_data.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 507 entries, 0 to 506
Data columns (total 21 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   author_name                    462 non-null    object
 1   medium                         495 non-null    object
 2   published_date                 469 non-null    object
 3   type_of_murder                 507 non-null    object
 4   name_of_victim                 504 non-null    object
 5   age                            312 non-null    float64
 6   date_of_murder                 43 non-null     object
 7   name_of_suspect                314 non-null    object
 8   suspect_relationship           505 non-null    object
 9   type_of_femicide               398 non-null    object
 10  murder_scene                   469 non-null    object
 11  mode_of_killing                441 non-null    object
 12  circumstance                   289 non-null    object
 13  status_on_article_date         377 non-null    object
 14  court_date_(first_appearance)  57 non-null     object
 15  verdict_date                   33 non-null     object
 16  verdict                        38 non-null     object
 17  years_of_sentence              18 non-null     float64
 18  days_to_verdict                34 non-null     float64
 19  area                           503 non-null    object
 20  county                         503 non-null    object
dtypes: float64(3), object(18)
memory usage: 83.3+ KB

In [ ]:
df.describe()

              age  years_of_sentence  days_to_verdict
count  312.000000          18.000000        34.000000
mean    32.894231          15.777778      1791.029412
std     16.263457           9.777258      1082.964604
min      6.000000           2.000000         0.000000
25%     22.750000          10.000000       875.750000
50%     28.000000          16.000000      1838.500000
75%     37.250000          20.000000      2709.000000
max     95.000000          40.000000      4061.000000

In [ ]:
df.isnull().sum()

author_name                       45
medium                            12
published_date                    38
type_of_murder                     0
name_of_victim                     3
age                              195
date_of_murder                   464
name_of_suspect                  193
suspect_relationship               2
type_of_femicide                 109
murder_scene                      38
mode_of_killing                   66
circumstance                     218
status_on_article_date           130
court_date_(first_appearance)    450
verdict_date                     474
verdict                          469
years_of_sentence                489
days_to_verdict                  473
area                               4
county                             4
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
#data cleaning
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(r"[^\w\s]", "", regex=True)
    .str.replace(r"\s+", "_", regex=True)
)

In [ ]:
df['verdict'] = df['verdict'].replace(
    {
        'guilty': 'guilty',
    'not guilty': 'not_guilty',
    }
)

In [ ]:
df['court_date_first_appearance'] = pd.to_datetime(df['court_date_first_appearance'], errors='coerce', format='mixed')
df['date_of_murder'] = pd.to_datetime(df['date_of_murder'], errors='coerce', format='mixed')
df['published_date'] = pd.to_datetime(df['published_date'], errors='coerce', format='mixed')
df['verdict_date'] = pd.to_datetime(df['verdict_date'], errors='coerce', format='mixed')

In [ ]:
df['age'].fillna(df['age'].median(), inplace=True)
df['county'].fillna('Unknown', inplace=True)

/tmp/ipykernel_767/2150556631.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].median(), inplace=True)
/tmp/ipykernel_767/2150556631.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['county'].fillna('Unknown', inplace=True)

In [ ]:
df['year']= df['published_date'].dt.year

In [ ]:
#cases per county
df['county'].value_counts()

county
Nairobi            75
Nakuru             61
Kiambu             37
Muranga            19
Kakamega           17
Kirinyaga          16
Kisumu             15
Uasin Gishu        15
Meru               14
Kisii              14
Nyeri              14
Machakos           13
Kajiado            13
Kericho            12
Bungoma            10
Embu               10
Trans Nzoia        10
Siaya               9
Kitui               9
Nyandarua           9
Homa Bay            9
Mombasa             9
Nandi               8
Bomet               8
Elgeyo Marakwet     6
Taita Taveta        6
West Pokot          6
Laikipia            6
Migori              6
Homabay             5
Busia               5
Makueni             5
Kwale               4
Unknown             4
Isiolo              4
Nyamira             3
Vihiga              3
Mandera             2
Kilifi              2
Kapsabet            1
Imenti South        1
Baringo             1
Eldoret             1
Garissa             1
Lamu                1
Naivasha            1
Marsabit            1
Nanyuki             1
Narok               1
Tran Nzoia          1
Tharaka Nithi       1
Tana River          1
Turkana             1
Name: count, dtype: int64

In [ ]:
#relationship breakdown
df['suspect_relationship'].value_counts()

suspect_relationship
husband                          129
Boyfriend                        117
Husband                           90
Stranger/Unknown Relationship     89
Friend/Known to victim            22
Family Member                     17
Ex-husband                        16
Ex-boyfriend                      11
boyfriend                          7
ex-boyfriend                       6
ex-husband                         1
Name: count, dtype: int64

In [ ]:
#mode of killing
df['mode_of_killing'].value_counts()

mode_of_killing
stabbed           143
blunt force        74
hacked             67
strangled          54
shot               31
sexual assault     18
other              15
burned             14
Stabbed            11
Strangled          10
Blunt force         3
Hacked              1
Name: count, dtype: int64

In [ ]:
#verdict outcomes
df['verdict'].value_counts()

verdict
guilty        24
Guilty        10
Not Guilty     2
15 years       1
Not guilty     1
Name: count, dtype: int64